version: "3"
services:

  mysql:
    image: mysql:8.0
    container_name: c137_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: fbackend
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      MYSQL_INITDB_CHARACTER_SET: utf8mb4
      MYSQL_INITDB_COLLATION: utf8mb4_unicode_ci
      TZ: Asia/Shanghai
    networks:
      c137_net:
        aliases:
          - c137_mysql

  redis:
    image: redis
    container_name: c137_redis
    command: redis-server --requirepass test1234
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      c137_net:
        aliases:
          - c137_redis

  c137:
    build:
      context: ..
      dockerfile: docker_build/dockerfile

    container_name: c137
    ports:
      - "8888:8888"
#    restart: always
    environment:
      - TZ=Asia/Shanghai
      - c137_env=docker
    networks:
      c137_net:
        aliases:
        - c137_server
    volumes:
      - ..:/C137

networks:
  c137_net: